[package]
name = "d24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
aoc2022lib.workspace = true
bare_metal_modulo = "1.2.4"
pathfinding.workspace = true

[lints]
workspace = true
