[package]
name = "d23"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
aoc2022lib.workspace = true
itertools.workspace = true

[dev-dependencies]
test-case.workspace = true

[lints]
workspace = true
