[package]
name = "d19"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
libaoc.workspace = true
grb = "=2.0.2"
nom.workspace = true

[dev-dependencies]
test-case.workspace = true

[target.'cfg(any())'.dependencies]
grb-sys2 = "=10.1.0"

[lints]
workspace = true
